version: 0.2 
 
phases: 
  build: 
    commands: 
      - echo Build started on `date` 
      - gem install cfn-nag 
      - cfn_nag_scan --input-path nodes-asg-cfn.yml 
  post_build: 
    commands: 
      - echo Build completed on `date` 
artifacts: 
  files: 
    - nodes-asg-cfn.yml 
