version: 0.2 
 
phases: 
  install:
    runtime-versions:
      ruby: 2.6
      python: 3.7
  build: 
    commands: 
      - echo Build started on `date` 
      - pip install cfn-lint
      - gem install cfn-nag 
      - cfn_nag_scan --input-path nodes-asg-cfn.yml 
  post_build: 
    commands: 
      - echo Build completed on `date` 
artifacts: 
  files: 
    - nodes-asg-cfn.yml 
