version: 0.2 
 
phases: 
  install:  
    runtime-versions:
      python: 3.7
    commands: 
      - pip install ansible-lint 
  build: 
    commands: 
      - echo Build started on `date` 
      - ansible-lint webserver.yml 
#  post_build: 
#    commands: 
#      - aws s3 cp webserver.yml s3://darko-ansible-webserver/ 
#      - echo Build completed on `date` 
artifacts: 
  files: 
    - '**/*' 
